import type { Item } from '$lib/types';

const str = `minecraft:sugar/7
minecraft:glow_ink_sac/8
minecraft:blackstone/19686
betterend:mossy_glowshroom_sapling/13
minecraft:ender_pearl/188
minecraft:prismarine/285
create:potato_cannon/1
minecraft:ladder/25
minecraft:lead/5
computercraft:printed_book/1
minecraft:golden_leggings/4
minecraft:beef/178
minecraft:redstone/654
minecraft:tide_armor_trim_smithing_template/1
minecraft:leather/372
create:sand_paper/4
betterend:neon_cactus/95
minecraft:golden_sword/5
create:mechanical_drill/93
minecraft:golden_axe/1
betterend:flamaea/22
minecraft:kelp/261
minecraft:nether_gold_ore/4
create:copper_valve_handle/2
computercraft:printed_page/2
minecraft:potato/1322
minecraft:warped_fungus_on_a_stick/2
minecraft:white_wool/337
minecraft:skeleton_skull/1
create:chute/8
minecraft:coal_ore/4
minecraft:dandelion/6
supplementaries:sack/1
computercraft:speaker/1
create:golden_sheet/48
betterend:umbrella_tree_cluster/2
minecraft:paper/780
minecraft:rotten_flesh/532
minecraft:spruce_planks/374
minecraft:oak_sign/14
minecraft:stone_stairs/12
minecraft:brown_mushroom/775
betterend:ender_dust/3
minecraft:pumpkin_seeds/6
minecraft:torch/83
farmersdelight:cabbage_seeds/756
minecraft:copper_ore/21
create:track/14
minecraft:mossy_cobblestone/30
create:gantry_carriage/1
minecraft:diamond_helmet/2
minecraft:poisonous_potato/22
minecraft:bread/8
minecraft:crossbow/1
minecraft:carved_pumpkin/1
minecraft:stripped_oak_log/33
minecraft:podzol/1076
supplementaries:wrench/1
minecraft:lime_wool/15
minecraft:blue_wool/34
minecraft:shield/1
betterend:music_disc_grasping_at_stars/2
minecraft:wheat_seeds/489
supplementaries:soap/5
create:super_glue/3
minecraft:oak_fence/19
create:large_cogwheel/9
minecraft:spruce_sapling/128
betterend:helix_tree_bark/160
create:iron_sheet/37
minecraft:iron_nugget/502
minecraft:rail/16
minecraft:trapped_chest/7
minecraft:cobblestone_stairs/6
minecraft:redstone_torch/15
friendsandfoes:totem_of_freezing/1
computercraft:cable/20
minecraft:spruce_log/858
minecraft:beetroot/2
create:andesite_casing/42
create:portable_storage_interface/1
minecraft:bone_meal/1454
create:redstone_contact/3
minecraft:diamond_hoe/1
minecraft:cod/19
minecraft:totem_of_undying/3
create:andesite_funnel/2
minecraft:nether_brick_stairs/2
farmersdelight:straw/8
minecraft:leather_boots/3
supplementaries:flax/251
minecraft:rabbit_foot/2
create:mechanical_harvester/2
minecraft:obsidian/273
minecraft:stone_slab/7
minecraft:copper_ingot/1447
minecraft:diamond/110
minecraft:cocoa_beans/29
create:item_vault/1
minecraft:white_tulip/5
minecraft:crying_obsidian/14
betterend:terminite_upgrade_smithing_template/1
createdeco:iron_support/4
betterend:mossy_glowshroom_crafting_table/1
minecraft:yellow_stained_glass/1
minecraft:chest/11
minecraft:magma_cream/68
minecraft:glowstone/7
betterend:netherite_upgrade_smithing_template/4
minecraft:sand/1804
minecraft:sponge/27
minecraft:spruce_fence/21
minecraft:dripstone_block/117
farmersdelight:rice/9
minecraft:bookshelf/1
create:brass_nugget/7
betterend:azure_jadestone/2
minecraft:yellow_dye/1
minecraft:oak_trapdoor/1
betterend:terminite_ingot/22
minecraft:coarse_dirt/2948
betterend:leather_handle_attachment_smithing_template/1
minecraft:white_bed/20
betterend:mossy_glowshroom_log/161
minecraft:honey_block/4
minecraft:chorus_fruit/15
minecraft:gold_nugget/364
minecraft:rabbit/34
create:brass_casing/2
minecraft:diamond_chestplate/1
betterend:umbrella_moss_tall/1
betterend:aeternium_ingot/3
minecraft:iron_door/7
betterend:flavolite/100
minecraft:charcoal/2265
betterend:blue_vine_lantern/22
create:brass_tunnel/1
betterend:thallasium_forged_plate/2
betterend:terminite_anvil/1
betterend:umbrella_tree_bark/8
create:precision_mechanism/5
betterend:music_disc_strange_and_alien/1
betterend:thallasium_anvil/1
minecraft:gray_carpet/26
create:brass_funnel/2
minecraft:spectral_arrow/10
minecraft:end_stone_bricks/56
minecraft:azalea/1
betterend:end_stone_smelter/2
minecraft:honeycomb_block/5
minecraft:purpur_pillar/34
betterend:glowing_pillar_luminophor/6
minecraft:cobblestone/70189
minecraft:iron_helmet/1
betterend:terminite_chestplate/1
betterend:lucernia_sapling/1
betterend:plate_upgrade_smithing_template/3
betterend:mossy_glowshroom_fur/2
minecraft:beetroot_seeds/7
minecraft:furnace/24
minecraft:red_wool/34
betterend:leather_stripe/3
minecraft:blue_ice/1
minecraft:shulker_shell/4
minecraft:mutton/23
betterend:pythadendron_sapling/21
betterend:music_disc_eo_dracona/1
minecraft:soul_sand/304
minecraft:tipped_arrow/198
minecraft:carrot/576
minecraft:cooked_beef/31
create:andesite_alloy/12
betterend:mossy_glowshroom_trapdoor/1
minecraft:egg/2
minecraft:prismarine_crystals/40
betterend:tenanea_planks/4
betterend:umbrella_moss/1
minecraft:nautilus_shell/1
minecraft:crafting_table/10
betterend:bolux_mushroom/3
betterend:filalux_wings/4
minecraft:prismarine_shard/90
minecraft:glowstone_dust/32
minecraft:purpur_block/118
minecraft:cactus/4502
minecraft:dirt/12143
minecraft:wooden_axe/1
betterend:mossy_glowshroom_planks/3
minecraft:dragon_head/3
minecraft:raw_copper/66
minecraft:player_head/96
betterend:handle_attachment_smithing_template/3
betterend:mossy_glowshroom_chest/2
minecraft:chiseled_polished_blackstone/3
farmersdelight:tomato_seeds/1313
minecraft:leather_chestplate/1
minecraft:birch_fence/1
supplementaries:checker_slab/6
minecraft:warped_nylium/6
friendsandfoes:totem_of_illusion/2
betterend:music_disc_endseeker/2
create:ochrum/107
minecraft:oak_slab/32
betterend:cave_moss/12
minecraft:purpur_slab/1
create:wrench/1
minecraft:bamboo/250
betterend:blossom_berry_seed/11
decorative_blocks:oak_palisade/390
betterend:mossy_glowshroom_bark/306
betterend:bulb_vine_seed/6
betterend:umbrella_tree_membrane/64
betterend:guidebook/1
create:zinc_nugget/113
betterend:raw_amber/3
betterend:pythadendron_log/51
minecraft:deepslate_lapis_ore/2
minecraft:shulker_box/5
minecraft:lectern/9
minecraft:white_dye/4
betterend:emerald_ice/7
minecraft:mushroom_stem/1
minecraft:netherite_upgrade_smithing_template/3
minecraft:gravel/4350
minecraft:dried_kelp/50
create:encased_fan/4
minecraft:green_dye/57
minecraft:end_stone/1149
betterend:sulphur_crystal/1
betterend:smaragdant_crystal_shard/3
betterend:shadow_berry/5
betterend:blue_vine_fur/1
betterend:brimstone/26
farmersdelight:rope/7
minecraft:deepslate/208
betterend:menger_sponge/120
create:water_wheel/2
minecraft:iron_horse_armor/2
minecraft:iron_chestplate/1
minecraft:warped_wart_block/6
minecraft:netherite_pickaxe/1
minecraft:sea_pickle/62
betterend:charnia_cyan/1
minecraft:ender_eye/8
minecraft:prismarine_bricks/320
betterend:virid_jadestone/2
minecraft:end_rod/2
betterend:blue_vine_seed/17
minecraft:white_banner/10
minecraft:wheat/1002
minecraft:glow_berries/83
create:gantry_shaft/61
minecraft:spruce_boat/1
betterend:purple_polypore/4
minecraft:oak_log/21026
betterend:aeternium_upgrade_smithing_template/3
betterend:pythadendron_bark/60
create:fluid_tank/5
minecraft:iron_shovel/2
create:vertical_gearbox/3
betterend:mossy_glowshroom_cap/2006
minecraft:grass_block/143
minecraft:iron_ingot/585
betterend:filalux_lantern/1
minecraft:chorus_flower/12
create:copper_casing/26
minecraft:golden_boots/4
minecraft:iron_sword/2
minecraft:magenta_wool/121
minecraft:polished_blackstone_bricks/64
minecraft:golden_helmet/2
infinitybuttons:stone_large_button/2
minecraft:packed_ice/16
minecraft:nether_brick_fence/1
minecraft:nether_bricks/11
minecraft:nether_quartz_ore/9
betterend:dragon_tree_sapling/54
minecraft:red_mushroom/808
minecraft:leather_leggings/2
farmersdelight:cabbage/749
minecraft:cauldron/6
minecraft:dark_prismarine/48
betterend:netherite_hammer/1
betterend:shadow_berry_raw/5
minecraft:oak_wood/4
minecraft:gold_ingot/409
minecraft:copper_block/458
minecraft:diamond_leggings/2
betterend:thallasium_ingot/294
supplementaries:bubble_blower/1
minecraft:oak_door/3
betterend:amber_moss/3
minecraft:ender_chest/1
betterend:tenanea_sapling/213
betterend:umbrella_tree_sapling/3
minecraft:orange_candle/3
minecraft:birch_sapling/3
minecraft:slime_ball/1742
minecraft:bee_nest/1
minecraft:birch_log/6
minecraft:jungle_door/2
minecraft:hay_block/28
minecraft:coast_armor_trim_smithing_template/1
minecraft:golden_carrot/32
minecraft:tripwire_hook/8
minecraft:brown_wool/106
minecraft:netherrack/6329
minecraft:andesite/60
minecraft:sunflower/78
supplementaries:flax_seeds/128
minecraft:rooted_dirt/2048
betterend:salteago/3
minecraft:shears/1
minecraft:acacia_log/15
minecraft:green_wool/57
betterend:blooming_cooksonia/14
farmersdelight:tomato/2087
minecraft:string/88
minecraft:warped_roots/15
computercraft:wireless_modem_normal/4
minecraft:flint_and_steel/3
minecraft:enchanted_book/6
minecraft:oak_sapling/1197
minecraft:basalt/374
minecraft:flint/694
minecraft:oak_button/397
betterend:shadow_grass/172
minecraft:red_dye/3
minecraft:netherite_scrap/1
minecraft:chain/4
minecraft:spruce_stairs/1
minecraft:acacia_sapling/2
minecraft:baked_potato/54
minecraft:magma_block/126
betterend:aurora_crystal/4
betterend:vaiolush_fern/33
minecraft:diamond_shovel/1
computercraft:turtle_normal/3
create:deployer/1
betterend:dragon_tree_bark/262
minecraft:bow/23
create:zinc_ingot/843
create:fluid_pipe/2
minecraft:cartography_table/1
minecraft:written_book/1
minecraft:spruce_sign/18
betterend:lumecorn_seed/12
betterend:dragon_tree_log/75
create:polished_rose_quartz/4
create:mechanical_mixer/1
minecraft:powered_rail/6
create:basin/1
betterend:end_moss/199
minecraft:iron_boots/1
create:limestone/486
minecraft:granite/2
computercraft:wireless_modem_advanced/5
supplementaries:item_shelf/1
betterend:thallasium_upgrade_smithing_template/3
supplementaries:gold_door/3
betterend:smaragdant_crystal/6
minecraft:feather/1
minecraft:diamond_horse_armor/1
minecraft:iron_leggings/2
supplementaries:timber_frame/4
computercraft:wired_modem_full/1
minecraft:cobblestone_slab/11
betterend:mossy_glowshroom_hymenophore/1072
minecraft:smithing_table/1
minecraft:ice/3
minecraft:porkchop/4
farmersdelight:rice_panicle/296
minecraft:pink_wool/54
minecraft:salmon/3
minecraft:wither_skeleton_skull/1
minecraft:netherite_ingot/3
minecraft:bucket/1
minecraft:cracked_polished_blackstone_bricks/73
betterend:tool_assembly_smithing_template/3
minecraft:loom/3
minecraft:raw_iron/21
minecraft:cyan_wool/25
supplementaries:goblet/1
create:shaft/88
minecraft:snow_block/272
minecraft:brown_dye/11
create:mechanical_crafter/33
betterend:tenanea_bark/272
create:zinc_ore/21
minecraft:stone_sword/4
supplementaries:notice_board/5
minecraft:blaze_rod/127
minecraft:smooth_stone_slab/351
minecraft:scaffolding/64
minecraft:emerald/342
create:cogwheel/23
betterend:lumecorn_rod/22
minecraft:smooth_stone/94
minecraft:acacia_planks/32
minecraft:red_tulip/3
minecraft:light_blue_wool/42
minecraft:oak_planks/1880
minecraft:golden_apple/11
minecraft:spire_armor_trim_smithing_template/1
minecraft:poppy/2
betterend:end_stone_stalactite/6
supplementaries:ash/190
supplementaries:flute/1
minecraft:nether_wart/796
minecraft:amethyst_block/50
betterend:lanceleaf_seed/34
minecraft:spruce_slab/17
minecraft:orange_tulip/1
betterend:pink_moss/15
betterend:end_lotus_seed/2
betterend:end_lotus_stem/66
minecraft:lapis_lazuli/2054
minecraft:stone/11340
minecraft:bone_block/18
farmersdelight:rotten_tomato/73
minecraft:apple/2247
farmersdelight:onion/1461
create:copper_sheet/51
minecraft:quartz/1440
minecraft:flowering_azalea/1
extended_drawers:quad_drawer/1
minecraft:arrow/30413
minecraft:deepslate_redstone_ore/9
betterend:iron_chandelier/1
minecraft:stick/1936
minecraft:rabbit_hide/1
create:raw_zinc/32
minecraft:stone_bricks/28
naturescompass:naturescompass/1
minecraft:glass/222
minecraft:golden_chestplate/2
create:piston_extension_pole/356
minecraft:snout_armor_trim_smithing_template/4
minecraft:lever/2
create_enchantment_industry:disenchanter/2
minecraft:smooth_basalt/5
betterend:rutiscus/1
minecraft:sugar_cane/3929
minecraft:gunpowder/612
minecraft:cobbled_deepslate/25501
betterend:helix_tree_log/43
minecraft:acacia_sign/6
minecraft:book/26
betterend:crystal_shards/704
minecraft:clay_ball/4696`;

export const items: Item[] = str
	.split('\n')
	.map((s) => s.split('/'))
	.map(([id, count]) => ({ id, count: parseInt(count) }));
